apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service:1.0.0
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "600m"
              memory: "1024Mi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:file:/workspace/config/application.yml,optional:file:/workspace/config/catalog-service.yml"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-secret
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: microservices-config
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
