apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      kafka:
        bootstrap-servers: kafka-kafka-bootstrap.kafka:9092

        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            spring:
              json:
                add:
                  type:
                    headers: true 
        consumer:
          auto-offset-reset: earliest
    
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    
          properties:
            spring:
              json:
                trusted:
                  packages: "*"    
                use:
                  type:
                    headers: true 
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,env,configprops
      endpoint:
        health:
          show-details: always
 
    security:
      jwt-properties:
        secret: ${JWT_SECRET}
        expiration-ms: 3600000
      whitelist: /auth/**,/oauth2/**,/swagger-ui/**,/v3/api-docs/**,/h2-console/**,/product/**,/batch, /error/**
    logging:
      level:
        com:
          microservices: TRACE
        org:
          springframework:
            security: DEBUG
            security.web.FilterChainProxy: DEBUG
            security.authorization: TRACE
            kafka: DEBUG
            kafka.clients.consumer: INFO
            kafka.listener: DEBUG
          hibernate:
            SQL: DEBUG
            orm:
              jdbc:
                bind: TRACE   
          type:
            descriptor:
              sql: TRACE


  product-service.yml: |-
    server:
     servlet:
       context-path: /api/product
    spring:
      sql:
        init:
          mode: always
      application:
        name: product-service
      datasource:
        url: jdbc:h2:mem:productdb
        driverClassName: org.h2.Driver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}  
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        defer-datasource-initialization: true
      h2:
        console:
          enabled: true


  cart-service.yml: |-
    server:
     servlet:
       context-path: /api/cart
    app:
      environment: prod
    spring:
      application:
        name: cart-service
      cloud:
        kubernetes:
          discovery:
            enabled: true
      datasource:
        url: jdbc:h2:mem:cartdb
        driverClassName: org.h2.Driver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}  
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop
        show-sql: true
      h2:
        console:
          enabled: true

    feign:
      client:
        config:
          catalog-service:
            connect-timeout: 5000
            read-timeout: 5000
 

  order-service.yml: |-
    server:
     servlet:
       context-path: /api/order
    app:
      environment: prod
    spring:
      application:
        name: order-service
      cloud:
        kubernetes:
          discovery:
            enabled: true
      datasource:
        url: jdbc:h2:mem:orderdb
        driverClassName: org.h2.Driver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}  
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
          ddl-auto: create-drop
        show-sql: true
      h2:
        console:
          enabled: true
    
    feign:
      client:
        config:
          cart-service:
            connect-timeout: 5000
            read-timeout: 5000
         

  user-service.yml: |-
    server:
     servlet:
       context-path: /api/user
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: http://localhost:8080/api/user/auth/google/callback
    user-management:
      database:
        enable: false
      google:
        enable: true
    spring:
      application:
        name: user-service
      datasource:
        url: jdbc:h2:mem:userdb
        driverClassName: org.h2.Driver
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}  
      jpa:
        hibernate:
          ddl-auto: create
        defer-datasource-initialization: true
        show-sql: true
      h2:
        console:
          enabled: true
      sql:
        init:
          mode: always


  mail-service.yml: |-
    server:
      servlet:
        context-path: /api/mail
    
    spring:
      mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
  